version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: node dist/main
    ## Image Tag
    image: brainfolio-api_web
    env_file:
      - .env
    ports:
      - "5000:5000"
    