version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used 
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: 
          name: Get Environment Variables from CircleCI
          command: |
            bash scripts/getEnv.sh
      

      - run: 
          name: Get Service Account Key from environment Variables
          command: |
            bash scripts/getServiceAccount.sh


      - run: 
          name: Run e2e test
          command: |
            npm run test:e2e

      - run:
          name: Push to master branch
          command: |
            git checkout testBranch
            git merge testBranch


      # - run:
      #     name: Install Docker Compose
      #     command: |
      #       curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
      #       chmod +x ~/docker-compose
      #       sudo mv ~/docker-compose /usr/local/bin/docker-compose

 

      # - run:
      #     name: Build docker 
      #     command: |
      #       ls -a
      #       docker-compose up
        